
# May be overwritten in .github/actions/hugo.yml 
# when deploying to gh pages
baseURL = 'https://qgis.org/'
languageCode = 'en-us'
title = 'QGIS Web Site'
theme = 'qgis'

# Folders in these folders get published automatically
staticDir = ['static']


[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
  # See readme for submenu notes
  submenu = 'submenus'

[params]
# Brand colours:
primary1 = "#589632"
primary2 = "#f0e64a"
primary3 = "#ee7913"
primary4 = "#93b023"
primary5 = "#589632"
complementary1 = "#55828b"
complementary2 = "#395c6b"
complementary3 = "#395c6b"
complementary4 = "#285238"
complementary5 = "#a7cecb"
light1 = "#fbfbfb"
light2 = "#eeeeee"
dark1 = "#999999"
dark2 = "#444444"
# Brand fonts
heading-font = "'Montserrat', sans-serif"
text-font = "'Work Sans', sans-serif"

# This will cause html in markdown files to be rendered directly
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# See https://gohugo.io/content-management/menus/
[menu]
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -110
  #pre = "<i class='fa-solid fa-clipboard-question mr-1'></i>"
  
[[menu.main]]
  name = "Community"
  url = "/community/"
  weight = -110 # Sets the menu order 
  #pre = "<i class='fa-solid fa-people-group mr-1'></i>"

[[menu.main]]
  name = "Resources"
  url = "/hub/"
  weight = -110 # Sets the menu order 
  #pre = "<i class='fa-solid fa-handshake-angle mr-1'></i>"

[[menu.main]]
  name = "Downloads"
  url = "/downloads/"
  #pre = "<i class='fa-solid fa-circle-down mr-1'></i>"
  weight = -110 # Sets the menu order 

[[menu.main]]
  name = "Value"
  url = "/value-proposition/"
  #pre = "<i class='fa fa-heart mr-1'></i>"
  weight = -110 # Sets the menu order 

# Submenus are done this way: parent -> identifier
[[menu.main]]
  parent = "Resources"
  name = "Documentation"
  url = "/documentation/documentation-overview/"
  weight = -120
  #pre = "<i class='fa-brands fa-windows mr-1'></i>"

[[menu.main]]
  parent = "Downloads"
  name = "Windows"
  url = "/download-windows/"
  weight = -120
  #pre = "<i class='fa-brands fa-windows mr-1'></i>"

[[menu.main]]
  parent = "Downloads"
  name = "macOS"
  url = "/download-mac/"
  weight = -120  
  # pre = "<i class='fa-brands fa-apple mr-1'></i>"

[[menu.main]]
  parent = "Downloads"
  name = "Linux"
  url = "/download-linux/"
  weight = -120  
  # pre = "<i class='fa-brands fa-linux mr-1'></i>"

[[menu.learning]]
  name = "Documentation"
  url = "/documentation/documentation-overview/"
  weight = -110
  #pre = "<i class='fa-solid fa-clipboard-question mr-1'></i>"
  [menu.learning.params]
    submenu = "documentation"


[outputs]
  home = ["HTML", "RSS", "JSON"]

