name = "qgis"
description = "The theme for the official QGIS.org web site"
license = "MIT"
source_repo = "https://github.com/kartoza/hugo-watcher"
tags = ["blog", "purecss"]
min_version = 0.14

[author]
    name = "QGIS.ORG"
    twitter = "http://twitter.com/qgis"
    url = "http://github.com/QGIS"

